### PR TITLE
Added support for Fenix 7 (all models) and  Forerunner 255 / 55 /  945 LTE / 955

### PR DESCRIPTION
**Pull request by dliedke**
Tested with Fenix 7X Solar Sapphire edition and worked perfectly.

### CODE REVIEW

**Comment by AbhiKafle123** [comment]
Hello @dliedke, Is there a way to upload this locally and sideload to your watch?

**Comment by dliedke** [comment]
Yes, you may clone the project, compile to prg for your device type and copy to Garmin/apps directory

**Comment by Arthaey** [comment]
Will this be available from the app store soon? I'd like to use this app on my Forerunner 955. Thanks!

**Comment by dliedke** [comment]
@AbhiKafle123  and @Arthaey I uploaded the new project to Garmin Store. When it is available for everybody I will let you know. (up to 3 days for Garmin to approve it)

**Comment by dliedke** [comment]
@AbhiKafle123 and @Arthaey

Dear dliedke - Congratulations!

Your app submission to the Connect IQ store has been approved. It may take up to 24 hours for the app to appear in the store for download. To access your app submission, go to: https://apps.garmin.com/en-US/apps/c5fc5ea5-7d12-4fb9-be9c-701663a39db7.

Sincerely,

- The Garmin Connect IQ Team

**Pull request closed without merging**
